### ISSUE TITLE
Do we want srdfdom to be standalone (no-ROS) package?

### ISSUE THREAD

**Issue by 130s** [moveit/srdfdom#16]
Looking at [package.xml](https://github.com/ros-planning/srdfdom/blob/a1dd5324cf15117fd6818f4c3e9d6b3ea2f7f7a0/package.xml), it looks like `srdfdom` is not and has not been depending on ROS, but searching the code lets me spot [a line](https://github.com/ros-planning/srdfdom/blob/503a8948162c7958ad2719c9e3bba19877ef0115/src/srdfdom/srdf.py#L220) in a method that depends on `rospy`, and the method is used by `scripts/display_srdf`.

I can't think of much benefit wrt to the effort of making it standlone, since `srdf` is primarily used only in MoveIt! (correct if wrong) and MoveIt! is ROS-based.

**Comment by v4hn** [comment]
I don't think it's even a good idea to make it stand-alone. It should remain a ROS package that we distribute together with the rest of MoveIt.
However, I do see the merit of handling it as a library, because it _is_ parsing xml, not publishing messages.
So +1 to remove ROS dependencies and -1 on making it standalone.

**Comment by rhaschke** [comment]
When there is no need by the community to have srdfdom released independently from ROS, we shouldn't take the effort. Nevertheless, at some point users might like to use srdfdom in a similar fashion as urdfdom parsers - independently of ROS. Hence, we shouldn't add more ROS dependencies.The one you spotted, @130s, considers loading from the parameter server. Similar functionality is available in package `robot_model` considering urdf.

**Comment by davetcoleman** [comment]
-1 to standalone, that causes so much headache for any future modifications we might want to make to the format, essentially making it impossible due to each ROS distro spanning several Ubuntu distros.

I'd love to see better semantics added to SRDFDom for grippers and humanoids with feet - I even have forks that do just that

**Comment by v4hn** [comment]
On Fri, Aug 26, 2016 at 11:14:54AM -0700, Dave Coleman wrote:

> I'd love to see better semantics added to SRDFDom for grippers and humanoids with feet - I even have forks that do just that

Where?? Sounds interesting!

**Comment by davetcoleman** [comment]
I might have slightly over-promised... for the humanoid walking work I've done, I modified the SRDF in this simple way:

https://github.com/davetcoleman/srdfdom/commit/82f768b0fd3a2d063c6c5edfdaa46ff2ff9db08f

For grasping, we developed (used for [many robots](https://github.com/davetcoleman/moveit_simple_grasps/tree/indigo-devel/config)) a [config yaml file](https://github.com/davetcoleman/moveit_simple_grasps/blob/indigo-devel/config/baxter_grasp_data.yaml) that would be much better suited in the SRDF IMHO

**Comment by davetcoleman** [comment]
Closing since it sounds like there is not enough interest / its not a good idea to make the package standalone
